name: Component testing

on:
  push:
    branches:
      - production
      - development
      - staging

  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          component: true
  coverage-report:
    runs-on: ubuntu-latest
    needs: [cypress-run]
    steps:
      - name: Generate Code Coverage report
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: $2b$10$POPC3moPq89kKw2oYkqDieVu60V.riVOVcbcDbhguCDaU86QnCOiW:39308071
          lcov-file: './coverage/lcov.info'
          send-summary-comment: true
          show-annotations: 'warning'
